print("cow says I love you Nancy")
print("____________________\n")
print("| I love you Nancy |\n")
print("==================\n")
print("                  \ \n")
print("                   \ \n")
print("                     ^__^ \n")
print("                     (oo)\_______ \n")
print("                     (__)\       )\/\ \n")
print("                         ||----w | \n")
print("                         ||     || \n")